apiVersion: apps/v1

kind: Deployement

metadata:

  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  strategy:
    type: Rollingupdate
    rolingupdate:
      maxSurge: 1
      maxUnavaible: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metada:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18.0
        ports:
        - containerPort: 80

env:
  - name: LOG_LEVEL
    value: "DEBUG"

