apiVersion: v1

kind: Pod

metadata: 
  name: app-color
  labels: 
   app: web

spec:

  containers:
  - name: web-app-color
    image: mmumshad/simple-webapp-color
    ports:
     - containerPort: 8080

    env:
     - name: APP_COLOR
       value: red 
