apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: nginx
    image: nginx:1.17-alpine
  - name: inspect
    image: alpine:3.10
    command: ["sleep","3600"]
~                             
