apiVersion: v1
kind: Pod
metadata:
  name: webpodAff
spec:
  containers:
  - name: nginx
    image: nginx:1.17-alpine
  affinity:
    nodeAffinity:
     requiredDuringscheldulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.iso/hostname
         operator: In
         values:
         - worker1
         - worker2
     preferredDuringSchedulingExecution:
     - weight: 1
       prference:
        matchExpressions:
        - key: disktype
          operator: In
          values:
          - ssd
~                                
