apiVersion: v1

kind: Pod

metadata:
  namespace: production
  name: pod-red
  labels:
       app: web

spec: 
  containers: 
    - name: cont-red1
      image: mmumshad/simple-webapp-color:latest
      ports: 
      - containerPort: 8080
      env:
      - name:  APP_COLOR
        value: red
      
      
