apiVersion: v1

kind: Pod

metadata:
  namespace: production
  name: pod-blue
  labels:
       app: web

spec: 
  containers: 
    - name: cont-blue1
      image: mmumshad/simple-webapp-color
      ports: 
      - containerPort: 8080
      env:
      - name:  APP_COLOR
        value: blue
      
      
