apiVersion: v1

kind: Service

metadata: 
  nom: service-nodeport-web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    npdePort: 3008
    
