apiVersion: v1

kind: Pod

metadata:

  name: inspect

spec:
  containers:
  - name: inspect
    image: alpine:3.10
    command: ["sleep","3600"]
~                                                                                                                                  
~                                
